### ISSUE TITLE
database credentials through secrets

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#229]
I am installing skyportal on spin at NERSC using docker.  Sensitive information, such as the database password, is handled using docker secrets.  It would be convenient if skyportal could pick up the database user, password, and name using that infrastructure.

**Comment by stefanv** [comment]
It looks like secrets can be mapped to files with something like:

```
$ docker service create \
     --name web \
     --secret source=docker.yaml,target=/skyportal_env/site.conf
     skyportal:web \
     sh -c 'bash -c "source /skyportal_env/bin/activate && \
             (make log &) && \
             make run_production"'
```

Would this solve your problem?  [Here](https://docs.docker.com/engine/swarm/secrets/#intermediate-example-use-secrets-with-a-nginx-service) is the documentation I referenced.

**Comment by AlexGKim** [comment]
Stefan, I did try the something like above but it didn't work.  The difference being that the secrets are in my docker-compose file and the shell command is in the Dockerfile.  If I understand your suggestion, skyportal picks up database information from a file in skyportal_env/site.conf?

I would like to confirm that the contents of docker.yaml should look like

database:
    database: skyportal
    host: db
    port: 5432
    user: skyportal
    password: PASSWORD

**Comment by stefanv** [comment]
That is correct, presuming you have the correct spacing in there:

```
database:
    database: skyportal
    host: db
    port: 5432
    user: skyportal
    password: PASSWORD

server:
    url: http://localhost:5000
```

**Comment by AlexGKim** [comment]
In your original post, there was no mention of `config.yaml`.  Could you specify what should have this name?  `site.conf`?

**Comment by stefanv** [comment]
The configuration file [location is currently hardcoded](https://skyportal.io/docs/setup.html#additional-configuration).  It is trivial to change, but I'd recommend keeping it for now.

**Comment by AlexGKim** [comment]
spin uses rancher secrets, not docker secrets.  It seems that rancher only allows secrets in its default directory.

**Comment by rcthomas** [comment]
Can the password just be overridden by an environment variable?  Then the config YAML file doesn't have to be stuffed into a secret.  The config itself should probably be managed in revision control for a deployment anyway, and really only sensitive stuff should go into the secret.  Can the entrypoint just add [file_env](https://github.com/docker-library/postgres/blob/master/9.6/docker-entrypoint.sh#L9) which itself comes from PostgreSQL's container anyway?

Then just something to allow setting of the credential if the variable is defined, overriding whatever's in the config.  Would this be an OK PR?

Alternatively I suppose the YAML could be created programmatically in the entrypoint.

**Comment by stefanv** [comment]
We typically don't pass passwords through environment variables because those are often easily revealed.

Here is a workaround, if you want to leverage a special secret configuration that just contains the password:

```
export FLAGS="--config=config.yaml --config=secret.yaml"
PYTHONPATH=. supervisord -c baselayer/conf/supervisor/supervisor.conf
```

(We read FLAGS in our supervisord config and append them to all invocations of our tools.)

**Comment by AlexGKim** [comment]
I get the following message when I add these lines...

Error: The directory named as part of the path log/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h

**Comment by stefanv** [comment]
Which directory are you launching supervisord from?

**Comment by AlexGKim** [comment]
I am launching this from /skyportal/

Going into the image and executing the command I get the following, which may be informative.

> skyportal@a3427d9e7e29:/skyportal$ PYTHONPATH=. supervisord -c baselapervisor/supervisor.conf
Error: Format string '/usr/bin/env python baselayer/services/webpack.py %(ENV_FLAGS)s' for 'program:webpack.command' contains names ('ENV_FLAGS') which cannot be expanded. Available names: ENV_GPG_KEY, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_LS_COLORS, ENV_PATH, ENV_POSTGRES_DB, ENV_POSTGRES_PASSWORD_FILE, ENV_POSTGRES_USER, ENV_PWD, ENV_PYTHONPATH, ENV_PYTHON_PIP_VERSION, ENV_PYTHON_VERSION, ENV_SHLVL, ENV_TERM, ENV__, group_name, here, host_node_name, process_num, program_name in section 'program:webpack' (file: 'baselayer/conf/supervisor/supervisor.conf')
For help, use /usr/bin/supervisord -h

**Comment by stefanv** [comment]
Yes, you will need: `PYTHONPATH=. FLAGS="" supervisord -c baselayer/conf/supervisor/supervisor.conf`

**Comment by AlexGKim** [comment]
The above didn't work for me.

Sorry I am now going backward rather than forward and am no longer able to build the docker image on my local computer, when I had been able to before.  In `baselayer/Makefile` there appears there should be another subdirectory baselayer?

>baselayer/Makefile:29: recipe for target 'dependencies' failed
make: *** [dependencies] Error 1
make: Entering directory '/skyportal/baselayer'
/bin/bash: line 0: cd: baselayer: No such file or directory
make: *** [dependencies] Error 1

**Comment by stefanv** [comment]
No, the baselayer makefile is called from the skyportal directory, so ./baselayer is correct.  Make sure the git submodule is initialized (should be done automatically, but you can also do `git submodule --init && git submodule update`.

How did the command I gave above fail?

**Comment by AlexGKim** [comment]
The baselayer issue is resolved.  It turned out to be a docker issue.

I do still have the error encountered before when building the docker image even following your updated instructions.

>Step 15/18 : RUN PYTHONPATH=. FLAGS="--config=config.yaml --config=secret.yaml" supervisord -c baselayer/conf/supervisor/supervisor.conf
 ---> Running in 63f94a414fc3
Error: The directory named as part of the path log/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h
The command '/bin/sh -c PYTHONPATH=. FLAGS="--config=config.yaml --config=secret.yaml" supervisord -c baselayer/conf/supervisor/supervisor.conf' returned a non-zero code: 2

**Comment by stefanv** [comment]
I see why, try:

```
make paths
make fill_conf_values
PYTHONPATH=. FLAGS="--config=config.yaml --config=secret.yaml" supervisord -c baselayer/conf/supervisor/supervisor.conf
```

**Comment by AlexGKim** [comment]
The new instructions work but doesn't return during `docker image build`.  These commands should not be in `Dockerfile` but elsewhere?

**Comment by stefanv** [comment]
Correct, this is your new `ENTRYPOINT`.

**Comment by AlexGKim** [comment]
Thanks.  I am making progress.  I now get the following error, which has the interesting message `ValueError: '/run/secrets/secret.yaml' does not start with '/skyportal'`

>Welcome to SkyPortal v0.9.dev0 (https://skyportal.io)

[23:27:51 baselayer] Compiling configuration templates
Traceback (most recent call last):
  File "./baselayer/tools/fill_conf_values.py", line 30, in <module>
    fill_config_file_values(args.template_paths)
  File "./baselayer/tools/fill_conf_values.py", line 14, in fill_config_file_values
    env, cfg = load_env()
  File "/skyportal/baselayer/app/env.py", line 36, in load_env
    cfg = load_config(config_files=env.config or [])
  File "/skyportal/baselayer/app/config.py", line 80, in load_config
    cfg = Config(all_configs)
  File "/skyportal/baselayer/app/config.py", line 23, in __init__
    config_names = [Path(c).relative_to(cwd) for c in config_files]
  File "/skyportal/baselayer/app/config.py", line 23, in <listcomp>
    config_names = [Path(c).relative_to(cwd) for c in config_files]
  File "/usr/local/lib/python3.6/pathlib.py", line 874, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/run/secrets/secret.yaml' does not start with '/skyportal'
baselayer/Makefile:56: recipe for target 'fill_conf_values' failed
make[1]: *** [fill_conf_values] Error 123
Makefile:61: recipe for target 'fill_conf_values' failed
make: *** [fill_conf_values] Error 2

**Comment by stefanv** [comment]
@AlexGKim That looks like a bug on our side.  @acrellin can you confirm?

**Comment by stefanv** [comment]
@AlexGKim Can you try the latest Git version of SkyPortal and see if that works for you?

**Comment by stefanv** [comment]
(Please make sure you've run `git submodule update`.)

**Comment by acrellin** [comment]
This is working for me now using the latest baselayer and specifying an external config file path in `load_config`, e.g. `load_config('/tmp/config.yaml')`

**Comment by AlexGKim** [comment]
The behavior is much better, the secret file is now found.  However authentication still does not work.  When I look in the container, I find that the secret file is NOT the secret file I put in.  This may be a rancher issue, but I would like to check that there should be no reading and overwriting of that file within skyportal.

**Comment by stefanv** [comment]
The Dockerfile has this command *while building the image*:  `cp docker.yaml config.yaml`.  But you should not run into that.  If it is a problem, just remove that line.

**Comment by AlexGKim** [comment]
The above problem is solved.  Was a rancher issue.

At what point is the skyportal_env directory created?  It isn't in the repository and the setup instructions say

>git clone https://github.com/skyportal/skyportal.git
cd skyportal/
virtualenv skyportal_env
source skyportal_env/bin/activate

**Comment by AlexGKim** [comment]
In doing some experimentation trying to access the database I get the following error, which I think has to do with the --no-password flag when I indeed do have a password.

> !!! Error accessing database:
> 
> The most common cause of database connection errors is a
> misconfigured `pg_hba.conf`.
> 
> We tried to connect to the database with the following parameters:
> 
>   database: skyportal
>   username: skyportal
>   host:     db
>   port:     5432
> 
> The postgres client exited with the following error message:
> 
> ------------------------------------------------------------------------------
> psql: fe_sendauth: no password supplied
> ------------------------------------------------------------------------------
> 
> Please modify your `pg_hba.conf`, and use the following command to
> check your connection:
> 
>   psql -U skyportal --no-password -h db -p 5432 -c 'SELECT 0;' skyportal
> 
> baselayer/Makefile:36: recipe for target 'db_init' failed
> make[1]: *** [db_init] Error 1
> Makefile:61: recipe for target 'db_init' failed
> make: *** [db_init] Error 2

**Comment by stefanv** [comment]
Please check the logs to see which configuration files are being loaded; it looks as though the config did not pick up the password.

**Comment by AlexGKim** [comment]
I am not sure this has anything to do with the above config file but I see this in `app.log`.  It is accessing the correct config file here but fails downstream.

>  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml
                /run/secrets/secret.yaml
Creating tables on database skyportal
Refreshed tables:
 - acls
 - roles
 - role_acls
 - users
 - tokens
 - token_acls
 - user_roles
 - groups
 - group_tokens
 - group_users
 - streams
 - stream_groups
 - sources
 - group_sources
 - telescopes
 - instruments
 - comments
 - photometry
 - spectra
 - thumbnails
 - usersocialauths
 - nonces
 - associations
 - codes
 - partials
Registering schemas with APISpec
Traceback (most recent call last):
  File "baselayer/services/app.py", line 27, in <module>
    app = app_factory(cfg, baselayer_handlers, baselayer_settings)
  File "/skyportal/skyportal/app_server.py", line 72, in make_app
    app.openapi_spec = openapi.spec_from_handlers(handlers)
  File "/skyportal/skyportal/openapi.py", line 67, in spec_from_handlers
    schema.register_components(openapi_spec)
  File "/skyportal/skyportal/schema.py", line 105, in register_components
    spec.components.schema(name, schema=schema)
  File "/usr/local/lib/python3.6/site-packages/apispec/core.py", line 80, in sch
ema
    ret.update(plugin.schema_helper(name, component, **kwargs) or {})
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.
py", line 165, in schema_helper
    json_schema = self.converter.schema2jsonschema(schema_instance)
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.p
y", line 265, in schema2jsonschema
    jsonschema = self.fields2jsonschema(fields, partial=partial, ordered=ordered
)
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.p
skyportal@0b8e6a7d250c:/skyportal/log$ tail app.log 
    json_schema = self.converter.schema2jsonschema(schema_instance)
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.py", line 265, in schema2jsonschema
    jsonschema = self.fields2jsonschema(fields, partial=partial, ordered=ordered)
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.py", line 289, in fields2jsonschema
    property = self.field2property(field_obj)
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/field_converter.py", line 166, in field2property
    ret.update(attr_func(field, ret=ret))
  File "/usr/local/lib/python3.6/site-packages/apispec/ext/marshmallow/field_converter.py", line 440, in list2properties
    field.inner if MARSHMALLOW_VERSION_INFO[0] >= 3 else field.container
AttributeError: 'RelatedList' object has no attribute 'inner'

**Comment by stefanv** [comment]
This looks like a problem that was fixed recently when we pinned Marshmallow versions: https://github.com/skyportal/skyportal/pull/222

But you are running the latest git master?

**Comment by AlexGKim** [comment]
The above is resolved with the latest git master.

I think we are almost there!  `make load_demo_data` and `tools/load_demo_data.py` does not seem to be picking up my secret password.

> (skyportal_env) skyportal@6becb29aca46:/skyportal$ make load_demo_data
> 
> Welcome to SkyPortal v0.9.dev0 (https://skyportal.io)
> 
>   Config files: baselayer/config.yaml.defaults
>                 config.yaml.defaults
> [✓] Connecting to database skyportal
> [·] Dropping all tablesDropping tables on database skyportal
> [✗] Dropping all tables
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
>     return fn()
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 365, in unique_connection
>     return _ConnectionFairy._checkout(self)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 822, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 554, in checkout
>     rec = pool._do_get()
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1250, in _do_get
>     self._dec_overflow()
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
>     raise value
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1247, in _do_get
>     return self._create_connection()
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
>     return _ConnectionRecord(self)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 499, in __init__
>     self.__connect(first_connect_check=True)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 701, in __connect
>     connection = pool._invoke_creator(self)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 437, in connect
>     return self.dbapi.connect(*cargs, **cparams)
>   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
>     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> psycopg2.OperationalError: fe_sendauth: no password supplied

**Comment by stefanv** [comment]
@acrellin Can you fix load_demo_data to correctly read the FLAGS environment and to correctly interpret configuration file specifiers via load_env?

**Comment by acrellin** [comment]
@stefanv Sure thing!

**Comment by acrellin** [comment]
@stefanv I'm not sure what the problem is you're referring to - `load_demo_data` just calls `load_env`, which should pick up any `--config` environment variables before calling `load_config`. What exactly do you think isn't happening that should? Is `load_env` not picking up the `--config` environment variable?

**Comment by stefanv** [comment]
See https://github.com/cesium-ml/baselayer/pull/65 and https://github.com/skyportal/skyportal/pull/239

**Comment by stefanv** [comment]
@AlexGKim can you try the latest version?  The problems you saw should be addressed.

**Comment by AlexGKim** [comment]
I just tried with the latest version (confirming that I have the latest master) and it doesn't work.

> [✗] Dropping all tables
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 365, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1250, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1247, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied

**Comment by acrellin** [comment]
Alex, can you post the contents of your pg_hba.conf file?

**Comment by AlexGKim** [comment]
This is from the database container.

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

host all all all md5
```

**Comment by acrellin** [comment]
I think adding the lines detailed on this page could solve the issue -
https://skyportal.io/docs/setup.html#installation-debian-based-linux
Let us know if that helps or not.

**Comment by AlexGKim** [comment]
I have not been able to figure out how to edit the `pg_hba.conf` file due to restrictions in spin and docker.

I have confirmed though that everything does work well when I turn off the password for the database.  Is this a clue that the `pg_hba.conf` is OK as is?

**Comment by AlexGKim** [comment]
I have added the two lines into `pg_hba.conf` and restarted the database (by removing the container and having the docker stack create a new one).  The error persists.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 365, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1250, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1247, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```

**Comment by stefanv** [comment]
We've done a lot of work on how configuration files are handled.  Can you please scan the output for any configuration file names, and check whether they are correct?

**Comment by AlexGKim** [comment]
Indeed /run/secrets/secret.yaml is missing, which is odd because it used to be there.

  Config files: baselayer/config.yaml.defaults
                config.yaml.defaults
                config.yaml


The secrets file is in the container.

Dockerfile has

ENTRYPOINT ["/skyportal/docker-entrypoint.sh”]

My docker-entrypoint.sh has

export FLAGS="--config=config.yaml --config=/run/secrets/secret.yaml"
make paths
make fill_conf_values
PYTHONPATH=. FLAGS="$FLAGS" supervisord -c baselayer/conf/supervisor/supervisor.conf

Alex

**Comment by stefanv** [comment]
When I run exactly the commands you provided above on the latest master branch, I see it loading the secret.yaml file.

**Comment by acrellin** [comment]
Alex, are you sure you're copying that file into the container correctly or
mounting the directory into the container?

**Comment by stefanv** [comment]
If the file cannot be loaded, SkyPortal should print a message to that effect.

**Comment by AlexGKim** [comment]
The secrets file is there and is done by rancher secrets, which is done by mounting the directory into the container.

A month ago this output text when I ran make load_demo_data used to include my secret.yaml file.  

 Config files: baselayer/config.yaml.defaults
               config.yaml.defaults
               config.yaml


I am looking for any change I could have made on my end that is responsible for  the change in behavior.

**Comment by AlexGKim** [comment]
I did pull the latest master and now get a new error message when running make load_demo_data.

(skyportal_env) skyportal@55382207d2b1:/skyportal$ make load_demo_data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/skyportal/skyportal/__init__.py", line 10, in <module>
    .split('T')[0].replace('-', '').split())
ValueError: not enough values to unpack (expected 2, got 0)

Welcome to SkyPortal v (https://skyportal.io)

Traceback (most recent call last):
  File "tools/load_demo_data.py", line 10, in <module>
    from skyportal.models import (init_db, Base, DBSession, Comment,
  File "/skyportal/skyportal/__init__.py", line 10, in <module>
    .split('T')[0].replace('-', '').split())
ValueError: not enough values to unpack (expected 2, got 0)
Makefile:58: recipe for target 'load_demo_data' failed
make: *** [load_demo_data] Error 1

**Comment by AlexGKim** [comment]
I think I have solved my earlier problem.  I need to edit my Makefile to include my extra path.

load_demo_data: ## Import example dataset
load_demo_data: FLAGS := $(if $(FLAGS),$(FLAGS),"--config=config.yaml --config=/run/secrets/secret.yaml”)

Alex

**Comment by stefanv** [comment]
@acrellin Please see above: related to versioning changes.

@AlexGKim No, that is the fallback value in case FLAGS is not set; you should not run into that.

**Comment by acrellin** [comment]
Alex, that ValueError you just pasted should be fixed by a patch I just
pushed in e77aece61744de3d59e1d4beca19b1ddfbba2dfe  --  apologies. Should
be working now.

**Comment by acrellin** [comment]
@stefanv it's fixed

**Comment by stefanv** [comment]
(I have just tested that setting that FLAGS environment variable does get picked up by `load_demo_data`.)

**Comment by stefanv** [comment]
@acrellin Swift work, thanks :)

**Comment by AlexGKim** [comment]
I picked up the latest master with the new skyportal/__init__.py but still get this error

(skyportal_env) skyportal@d41f3aa27175:/skyportal$ make load_demo_data
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/skyportal/skyportal/__init__.py", line 14, in <module>
    .split('T')[0].replace('-', '').split())
ValueError: not enough values to unpack (expected 2, got 0)

Welcome to SkyPortal v (https://skyportal.io)

Traceback (most recent call last):
  File "tools/load_demo_data.py", line 10, in <module>
    from skyportal.models import (init_db, Base, DBSession, Comment,
  File "/skyportal/skyportal/__init__.py", line 14, in <module>
    .split('T')[0].replace('-', '').split())
ValueError: not enough values to unpack (expected 2, got 0)
Makefile:58: recipe for target 'load_demo_data' failed
make: *** [load_demo_data] Error 1

**Comment by acrellin** [comment]
Hi Alex,

I'll try to get this fixed for you, apologies for the issue.  Is git
installed on the machine you're running this on?  And what's the OS?

**Comment by AlexGKim** [comment]
I am running SkyPortal in a docker container using ubuntu:18.04.  So I am not working directly with git on the machine this is running on.

Alex

**Comment by acrellin** [comment]
Alex, can you confirm that you're running the latest skyportal with commit
hash cdfa8dc573e02970c4a242e3e9b6ec36dd5c72ac ?   We've recently pushed
some changes up.

**Comment by stefanv** [comment]
@acrellin If git isn't found, we should just abort and let everything continue as-is.

**Comment by AlexGKim** [comment]
I also find that inside the docker container, the environment variable FLAGS is not set, despite the export FLAGS="--config=config.yaml --config=/run/secrets/secret.yaml” in the docker-entrypoint.sh

**Comment by AlexGKim** [comment]
SUCCESS!

I the secrets file directly into the command in the Makefile.

        @PYTHONPATH=. python tools/load_demo_data.py $(FLAGS) --config=/run/secrets/secret.yaml

and I was able to successfully run make load_demo_data.

My original purpose that led to the opening of this issue was to have a password for the database.  Now that (I think) this is working, practically I think we can close this.  You may find a more elegant solution than mine.

**Comment by AlexGKim** [comment]
I will try this shortly and let you know.

I am encountering a new error when trying to add a user to a group through the website.

API Error: Could not fetch data from server. 

I am able to interact with SkyPortal through the API.

Alex

**Comment by stefanv** [comment]
Please check the output of `make log`: it records some more details of these errors.

**Comment by AlexGKim** [comment]
I was able to deduce what the problem is.  The username in SkyPortal is cap sensitive, whereas the google authentication user name (the e-mail address) is not cap sensitive.

Alex

**Comment by stefanv** [comment]
Interesting! So Google can sometimes return capitalized usernames? Would it be preferable for us to simply turn those into lower-case?

**Comment by AlexGKim** [comment]
A user sent me his e-mail capitalized but logged into SkyPortal uncapitalized.  This caused the problem  I believe (from a google search) that email addresses are cap insensitive.  So it may make sense for SkyPortal ID’s to follow the same convention.

I was using the exec form for entrypoint.  Based on  https://stackoverflow.com/a/37904830/214686 I switched to the shell form.  Even so I get the same error and going into the container the FLAGS environmental variable is not set.

Alex

**Comment by dannygoldstein** [comment]
Closing as this appears to be resolved - due to a capitalization issue (@AlexGKim priv comm).
